name: jwt
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
flutter_native_splash:
  image: images/logo.png
  color: "#ffffff"
  android_disable_fullscreen: true  //安卓下禁止全屏
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^3.2.0
  shared_preferences: ^2.0.5
  dio: ^3.0.9
  cookie_jar: ^1.0.0
  flutter_splash_screen: ^0.1.0
  sqflite: ^1.3.0
  flutter_bloc: ^6.1.1 #状态管理框架
  equatable: ^1.2.3 #增强组件相等性判断
  camera: ^0.8.1 #相机
  permission_handler: ^6.1.3
  path_provider: ^2.0.1
  fluttertoast: ^8.0.6
  event_bus: ^2.0.0
  lcfarm_flutter_umeng: ^0.1.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  #Flutter 国际化插件
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/local_database.db
    - assets/local_database_ajt.db
    - images/icon_splash_gb.png
    - images/icon_empty.png
    - images/icon_error.png
    - images/icon_bottom_sy.png
    - images/icon_bottom_sy_pressed.png
    - images/icon_bottom_rfcx.png
    - images/icon_bottom_rfcx_pressed.png
    - images/icon_bottom_yj.png
    - images/icon_bottom_yj_pressed.png
    - images/icon_bottom_wd.png
    - images/icon_bottom_wd_pressed.png
    - images/button_back.png
    - images/icon_begin.png
    - images/icon_menu.png
    - images/icon_login_background.png
    - images/icon_login.png
    - images/icon_yhm.png
    - images/icon_mima.png
    - images/icon_sum_house_count.png
    - images/icon_sum_people_count.png
    - images/icon_stretch_background.png
    - images/icon_stretch_down.png
    - images/icon_stretch_up.png
    - images/icon_ajt.png
    - images/icon_people_check.png
    - images/icon_house_check.png
    - images/icon_task_manage.png
    - images/icon_intelligence_manage.png
    - images/icon_info.png
    - images/icon_mine_bg.png
    - images/icon_police.png
    - images/icon_more.png
    - images/icon_ocr.png
    - images/icon_close.png
    - images/icon_select_true.png
    - images/icon_bg_identify_idcard.png
    - images/icon_card_bj.png
    - images/icon_head.png
    - images/icon_register.png
    - images/icon_unregister.png
    - images/icon_cart_title.png
    - images/icon_select.png
    - images/icon_ban.png
flutter_intl:
  enabled: true